import {
  FaCss3Alt,
  FaDocker,
  FaFigma,
  FaGitAlt,
  FaHtml5,
  FaJs,
  FaLinux,
  FaNodeJs,
  FaPhp,
  FaPython,
  FaReact,
  FaWordpress,
} from 'react-icons/fa'
import {
  SiAnsible,
  SiAstro,
  SiCanvas,
  SiDjango,
  SiElementor,
  SiGithubactions,
  SiGooglecloud,
  SiJupyter,
  SiKubernetes,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNotion,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiSass,
  SiStorybook,
  SiTailwindcss,
  SiTerraform,
  SiTensorflow,
  SiTypescript,
  SiUnity,
  SiWoocommerce,
} from 'react-icons/si'
import { FiCode, FiGrid, FiSearch, FiServer, FiUsers } from 'react-icons/fi'
import {
  TbBrandAzure,
  TbBrandCSharp,
  TbChartPie,
  TbFileExcel,
  TbPalette,
} from 'react-icons/tb'

const skillIcons = {
  FaCss3Alt,
  FaDocker,
  FaFigma,
  FaGitAlt,
  FaHtml5,
  FaJs,
  FaLinux,
  FaNodeJs,
  FaPhp,
  FaPython,
  FaReact,
  FaWordpress,
  FiCode,
  FiGrid,
  FiSearch,
  FiServer,
  FiUsers,
  SiAnsible,
  SiAstro,
  SiCanvas,
  SiDjango,
  SiElementor,
  SiGithubactions,
  SiGooglecloud,
  SiJupyter,
  SiKubernetes,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNotion,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiSass,
  SiStorybook,
  SiTailwindcss,
  SiTerraform,
  SiTensorflow,
  SiTypescript,
  SiUnity,
  SiWoocommerce,
  TbBrandAzure,
  TbBrandCSharp,
  TbChartPie,
  TbFileExcel,
  TbPalette,
}

export const getSkillIcon = (iconName) => {
  const Icon = skillIcons[iconName] || FiCode
  return <Icon aria-hidden='true' />
}
